name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          boost_version: 1.88.0
      - name: configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        env:
          BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}
      - name: build
        run: cmake --build build --parallel 2
      - name: test
        run: cd build && ctest -VV